<?php

namespace App\Filament\Resources\ThematiqueResource\RelationManagers;
use App\Filament\Resources\QuestionResource;
use App\Filament\Resources\ThematiqueResource;
use App\Models\Question;
use Filament\Forms;
use Filament\Tables;
use Filament\Forms\Components\Grid;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Toggle;
use Illuminate\Database\Eloquent\Model;
use Filament\Forms\Components\TextInput;
use Illuminate\Database\Eloquent\Builder;
use Filament\Forms\Components\BelongsToSelect;
use Filament\Tables\Filters\MultiSelectFilter;
class QuestionsRelationManager extends RelationManager
{
    protected static string $relationship = 'questions';
    protected static ?string $recordTitleAttribute = 'name';
    protected function canCreate(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }
    protected function canEdit(Model $record): bool
    {
        return false; // TODO: Change the autogenerated stub
    }
    protected function canDelete(Model $record): bool
    {
        return false; // TODO: Change the autogenerated stub
    }
    public function form(\Filament\Forms\Form $form): Filament\Forms\Form
    {
        return $form->schema([
            Grid::make(['default' => 0])->schema([
                TextInput::make('name')
                    ->rules(['max:255', 'string'])
                    ->unique('questions', 'name', fn(?Model $record) => $record)
                    ->placeholder('Name')
                    ->columnSpan([
                        'default' => 12,
                        'md' => 12,
                        'lg' => 12,
                    ]),
                TextInput::make('reponse')
                    ->rules(['max:255', 'string'])
                    ->placeholder('Reponse')
                    ->columnSpan([
                        'default' => 12,
                        'md' => 12,
                        'lg' => 12,
                    ]),
                TextInput::make('option1')
                    ->rules(['max:255', 'string'])
                    ->placeholder('Option1')
                    ->columnSpan([
                        'default' => 12,
                        'md' => 12,
                        'lg' => 12,
                    ]),
                Toggle::make('status')
                    ->rules(['boolean'])
                    ->columnSpan([
                        'default' => 12,
                        'md' => 12,
                        'lg' => 12,
                    ]),
            ]),
        ]);
    }
    public function table(\Filament\Tables\Table $table): Filament\Tables\Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')
                    ->label("Question")
                    ->url(function (?Question  $record){
                        return QuestionResource::getUrl('view', $record->id);
                    })
                    ->searchable()
                    ->limit(50),
                Tables\Columns\TextColumn::make('reponse')
                    ->label("Réponse")
                    ->searchable()
                    ->limit(50),
                Tables\Columns\TextColumn::make('option1')
                    ->label("Option 1")
                    ->searchable()
                    ->limit(50),
                Tables\Columns\TextColumn::make('option2')
                    ->label("Option 2")
                    ->limit(50),
                Tables\Columns\ToggleColumn::make('status')
                    ->label("Statut"),
            ]);
    }
}
