<?php

namespace App\Filament\Resources\QuestionResource\RelationManagers;
use App\Filament\Resources\ThematiqueResource;
use App\Models\Question;
use App\Models\Response;
use Filament\Forms;
use Filament\Tables;
use Filament\Forms\Components\Grid;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Toggle;
use Filament\Forms\Components\TextInput;
use Illuminate\Database\Eloquent\Builder;
use Filament\Forms\Components\BelongsToSelect;
use Filament\Tables\Filters\MultiSelectFilter;
use Illuminate\Database\Eloquent\Model;
class ResponsesRelationManager extends RelationManager
{
    protected static string $relationship = 'responses';
    protected static ?string $recordTitleAttribute = 'reponse';
    protected function canCreate(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }
    protected function canEdit(Model $record): bool
    {
        return false; // TODO: Change the autogenerated stub
    }
    protected function canDelete(Model $record): bool
    {
        return false; // TODO: Change the autogenerated stub
    }
    public function form(\Filament\Forms\Form $form): Filament\Forms\Form
    {
        return $form->schema([
        ]);
    }
    public function table(\Filament\Tables\Table $table): Filament\Tables\Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('question.thematique.name')
                    ->label("Thématique")
                    ->url(function (?Response  $record){
                        return ThematiqueResource::getUrl('view', $record->question->thematique_id);
                    })
                    ->limit(50),
                Tables\Columns\TextColumn::make('question.name')
                    ->label("Question")
                    ->searchable()
                    ->limit(50),
                Tables\Columns\TextColumn::make('reponse')
                    ->label("Réponse")
                    ->searchable()
                    ->limit(50),
                Tables\Columns\TextColumn::make('option1')
                    ->label("Option 1")
                    ->searchable()
                    ->limit(50),
                Tables\Columns\TextColumn::make('option2')
                    ->label("Option 2")
                    ->limit(50),
                Tables\Columns\ToggleColumn::make('status')
                    ->label("Statut"),
            ]);
    }
}
