<?php

namespace App\Filament\Resources\QuestionResource\RelationManagers;

use App\Filament\Resources\ThematiqueResource;
use App\Models\Question;
use Filament\Forms;
use Filament\Tables;
use Filament\Resources\{Form, Table};
use Filament\Forms\Components\Grid;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Toggle;
use Filament\Forms\Components\TextInput;
use Illuminate\Database\Eloquent\Builder;
use Filament\Forms\Components\BelongsToSelect;
use Filament\Tables\Filters\MultiSelectFilter;
use Filament\Resources\RelationManagers\RelationManager;
use Illuminate\Database\Eloquent\Model;

class ResponsesRelationManager extends RelationManager
{
    protected static string $relationship = 'responses';

    protected static ?string $recordTitleAttribute = 'reponse';

    protected function canCreate(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

    protected function canEdit(Model $record): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

    protected function canDelete(Model $record): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form->schema([

        ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('thematique.name')
                    ->label("Thématique")
                    ->url(function (?Question  $record){
                        return ThematiqueResource::getUrl('view', $record->thematique_id);
                    })
                    ->limit(50),

                Tables\Columns\TextColumn::make('name')
                    ->label("Question")
                    ->searchable()
                    ->limit(50),

                Tables\Columns\TextColumn::make('reponse')
                    ->label("Réponse")
                    ->searchable()
                    ->limit(50),

                Tables\Columns\TextColumn::make('option1')
                    ->label("Option 1")
                    ->searchable()
                    ->limit(50),

                Tables\Columns\TextColumn::make('option2')
                    ->label("Option 2")
                    ->limit(50),

                Tables\Columns\ToggleColumn::make('status')
                    ->label("Statut"),
            ]);
    }
}
