<?php

namespace App\Filament\Resources\QuestionResource\RelationManagers;

use App\Filament\Resources\ThematiqueResource;
use App\Models\Response;
use Filament\Forms\Form;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Model;

class ResponsesRelationManager extends RelationManager
{
    protected static string $relationship = 'responses';

    protected static ?string $recordTitleAttribute = 'reponse';

    protected function canCreate(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

    protected function canEdit(Model $record): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

    protected function canDelete(Model $record): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

    public function form(Form $form): Form
    {
        return $form->schema([

        ]);
    }

    public function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('question.thematique.name')
                    ->label('Thématique')
                    ->url(function (?Response $record) {
                        return ThematiqueResource::getUrl('view', ['record' => $record->question->thematique_id]);
                    })
                    ->limit(50),

                Tables\Columns\TextColumn::make('question.name')
                    ->label('Question')
                    ->searchable()
                    ->limit(50),

                Tables\Columns\TextColumn::make('reponse')
                    ->label('Réponse')
                    ->searchable()
                    ->limit(50),

                Tables\Columns\TextColumn::make('option1')
                    ->label('Option 1')
                    ->searchable()
                    ->limit(50),

                Tables\Columns\TextColumn::make('option2')
                    ->label('Option 2')
                    ->limit(50),

                Tables\Columns\ToggleColumn::make('status')
                    ->label('Statut'),
            ]);
    }
}
