<?php

namespace App\Filament\Resources;
use Filament\Resources\Resource;
use App\Filament\Resources\UtilisateurResource\Widgets\UtilisateurBonneReponseChart;
use App\Filament\Resources\UtilisateurResource\Widgets\UtilisateurMauvaiseReponseChart;
use App\Filament\Resources\UtilisateurResource\Widgets\UtilisateurOverview;
use App\Filament\Resources\UtilisateurResource\Widgets\ViewUtilisateurOverview;
use App\Models\Utilisateur;
use Faker\Provider\Text;
use Filament\{Tables, Forms};
use Filament\Forms\Components\Grid;
use Filament\Forms\Components\Card;
use Filament\Forms\Components\Toggle;
use Illuminate\Database\Eloquent\Model;
use Filament\Forms\Components\TextInput;
use App\Filament\Filters\DateRangeFilter;
use App\Filament\Resources\UtilisateurResource\Pages;
class UtilisateurResource extends Resource
{
    protected static ?string $model = Utilisateur::class;
    protected static ?string $navigationIcon = 'heroicon-o-user-group';
    protected static ?string $recordTitleAttribute = 'nom';
    public static function canCreate(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }
    public static function form(\Filament\Forms\Form $form): Filament\Forms\Form
    {
        return $form->schema([
            Card::make()->schema([
                Grid::make(['default' => 0])->schema([
                    TextInput::make('nom')
                        ->rules(['max:255', 'string'])
                        ->required()
                        ->placeholder('Nom')
                        ->columnSpan([
                            'default' => 12,
                            'md' => 12,
                            'lg' => 12,
                        ]),
                    TextInput::make('prenom')
                        ->rules(['max:255', 'string'])
                        ->required()
                        ->placeholder('Prenom')
                        ->columnSpan([
                            'default' => 12,
                            'md' => 12,
                            'lg' => 12,
                        ]),
                    TextInput::make('email')
                        ->rules(['email'])
                        ->required()
                        ->unique(
                            'utilisateurs',
                            'email',
                            fn(?Model $record) => $record
                        )
                        ->email()
                        ->placeholder('Email')
                        ->columnSpan([
                            'default' => 12,
                            'md' => 12,
                            'lg' => 12,
                        ]),
                    TextInput::make('phone')
                        ->rules(['max:255', 'string'])
                        ->required()
                        ->unique(
                            'utilisateurs',
                            'phone',
                            fn(?Model $record) => $record
                        )
                        ->placeholder('Phone')
                        ->columnSpan([
                            'default' => 12,
                            'md' => 12,
                            'lg' => 12,
                        ]),
                    Forms\Components\Select::make('sexe')
                        ->options([
                            'M' => 'Masculin',
                            'F' => 'Féminin',
                        ])
                        ->placeholder('Sélectionner le sexe')
                        ->columnSpan([
                            'default' => 12,
                            'md' => 12,
                            'lg' => 12,
                        ]),
                    Forms\Components\DatePicker::make('dob')
                        ->label('Date de naissance')
                        ->placeholder('Date de naissance')
                        ->columnSpan([
                            'default' => 12,
                            'md' => 12,
                            'lg' => 12,
                        ]),
                    Forms\Components\Select::make('ville_id')
                        ->relationship('ville', 'name')
                        ->label('Ville')
                        ->searchable()
                        ->placeholder('Sélectionner une ville')
                        ->columnSpan([
                            'default' => 12,
                            'md' => 12,
                            'lg' => 12,
                        ]),
                    Forms\Components\FileUpload::make('photo')
                        ->image()
                        ->directory('photos-utilisateurs')
                        ->columnSpan([
                            'default' => 12,
                            'md' => 12,
                            'lg' => 12,
                        ]),
                    TextInput::make('platform')
                        ->label('Plateforme (iOS/Android)')
                        ->disabled()
                        ->placeholder('Ex: android, ios')
                        ->helperText('Plateforme depuis laquelle l\'utilisateur s\'est inscrit')
                        ->visibleOn('edit')
                        ->columnSpan([
                            'default' => 12,
                            'md' => 6,
                            'lg' => 6,
                        ]),
                    TextInput::make('provider')
                        ->label('Méthode de connexion')
                        ->disabled()
                        ->placeholder('Ex: google, facebook')
                        ->helperText('Fournisseur d\'authentification sociale')
                        ->visibleOn('edit')
                        ->columnSpan([
                            'default' => 12,
                            'md' => 6,
                            'lg' => 6,
                        ]),
                    Toggle::make('status')
                        ->label('Actif')
                        ->rules(['boolean'])
                        ->required()
                        ->columnSpan([
                            'default' => 12,
                            'md' => 12,
                            'lg' => 12,
                        ]),
                ]),
            ]),
        ]);
    }
    public static function table(\Filament\Tables\Table $table): Filament\Tables\Table
    {
        return $table
            ->poll('60s')
            ->columns([
                Tables\Columns\TextColumn::make('nom')
                    ->label("Nom")
                    ->searchable()
                    ->limit(50),
                Tables\Columns\TextColumn::make('prenom')
                    ->label("Prénom")
                    ->searchable()
                    ->limit(50),
                Tables\Columns\TextColumn::make('email')
                    ->label("Email")
                    ->searchable()
                    ->limit(50),
                Tables\Columns\TextColumn::make('phone')
                    ->label("Téléphone")
                    ->searchable()
                    ->limit(50),
                Tables\Columns\TextColumn::make('ville.name')
                    ->label("Ville")
                    ->searchable()
                    ->sortable()
                    ->toggleable(),
                Tables\Columns\TextColumn::make('dob')
                    ->label("Date de naissance")
                    ->date('d/m/Y')
                    ->sortable()
                    ->toggleable(),
                Tables\Columns\ImageColumn::make('photo')
                    ->label("Photo")
                    ->circular()
                    ->toggleable(),
                Tables\Columns\IconColumn::make('status')
                    ->label("Statut")
                    ->boolean(),
                Tables\Columns\BadgeColumn::make('platform')
                    ->label("Plateforme")
                    ->colors([
                        'success' => 'android',
                        'info' => 'ios',
                    ])
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\BadgeColumn::make('provider')
                    ->label("Méthode")
                    ->colors([
                        'warning' => fn ($state) => $state !== null,
                    ])
                    ->formatStateUsing(fn (?string $state): string => $state ?: 'Email')
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('created_at')
                    ->label("Inscription")
                    ->date('d F Y H:i')
                    ->sortable()
            ])
            ->filters([
                DateRangeFilter::make('created_at'),
                Tables\Filters\TernaryFilter::make('status')
                    ->label('Statut')
                    ->placeholder('Tous')
                    ->trueLabel('Actifs')
                    ->falseLabel('Inactifs'),
            ])
            ->actions([
                Tables\Actions\ViewAction::make(),
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\DeleteBulkAction::make(),
            ])
            ->defaultSort('created_at', 'desc');
    }
    public static function getRelations(): array
    {
        return [
            UtilisateurResource\RelationManagers\AlertesRelationManager::class,
            UtilisateurResource\RelationManagers\ResponsesRelationManager::class,
        ];
    }
    public static function getWidgets(): array
    {
        return [
            UtilisateurOverview::class,
            ViewUtilisateurOverview::class,
            UtilisateurBonneReponseChart::class,
            UtilisateurMauvaiseReponseChart::class
        ];
    }
    public static function getPages(): array
    {
        return [
            'index' => Pages\ListUtilisateurs::route('/'),
            'create' => Pages\CreateUtilisateur::route('/create'),
            'view' => Pages\ViewUtilisateur::route('/{record}'),
            'edit' => Pages\EditUtilisateur::route('/{record}/edit'),
        ];
    }
}